version: "3.8"
services:

  traefik:
    image: "traefik:v2.11"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - TRAEFIK_HTTP_ROUTERS_API_RULE=Host(`traefik.localtest.me`)
      - TRAEFIK_ENTRYPOINTS_WEB_ADDRESS=:80
      - TRAEFIK_LOG_LEVEL=DEBUG
      - TRAEFIK_PROVIDERS_DOCKER_WATCH=true
      - TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT=true
      - TRAEFIK_API_DASHBOARD=true
      - TRAEFIK_HTTP_ROUTERS_API_ENTRYPOINTS=web
      - TRAEFIK_HTTP_ROUTERS_API_SERVICE=api@internal

  backend:
    build:
      context: ./backend
    environment:
      - FLASK_APP=/app/app.py
    ports:
      - "5000:5000"
    volumes:
      - ./backend/app:/app
    command: flask run --host=0.0.0.0 --port=5000

  calendar_and_email_service:
    build:
      context: ./backend
    environment:
      - FLASK_APP=/app/calendar_and_email.py
    volumes:
      - ./backend/app:/app
    working_dir: /app
    command: python calendar_and_email.py
    labels:
      - traefik.http.routers.calendar_and_email_service.rule=Host(`localtest.me`) && PathPrefix(`/events`)
      - traefik.http.services.calendar_and_email_service.loadbalancer.server.port=5001

  file_sharing_service:
    build:
      context: ./backend
    environment:
      - FLASK_APP=/app/file_sharing.py
    volumes:
      - ./backend/app:/app
    working_dir: /app
    command: python file_sharing.py

  guestlist_service:
    build:
      context: ./backend
    environment:
      - FLASK_APP=/app/guest_list.guestlist.py
    volumes:
      - ./backend/app:/app
    working_dir: /app/guest_list
    command: python guestlist.py
    labels:
      - traefik.http.routers.guestlist_service.rule=Host(`localtest.me`) && PathPrefix(`/guestlist`)
      - traefik.http.services.guestlist_ser.loadbalancer.server.port=5002
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/src
    command: npm start

    
